version: "3.8"
volumes:
  my-datavolume:
services:
  mysql-db:
    image: "bitnami/mysql:latest"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=one-time-secret
      - MYSQL_HOST=mysql-db
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - my-datavolume:/var/lib/mysql
  client:
    build: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server
  server:
    build: ./server
    # build:
    #   context: ./server
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - mysql-db
